import { PrismaClient } from '@prisma/client';
import { env } from './env';

// Global declaration to prevent multiple Prisma instances during hot-reload
const globalForPrisma = globalThis as unknown as { prisma: PrismaClient | undefined };

export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
  });

if (env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}

// In-Memory Resilient Fallback Store for Development
export interface FallbackUser {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  targetRole?: string | null;
  degreeName?: string | null;
  currentSemester: number;
  gpa?: number | null;
  role: 'STUDENT' | 'ADMIN';
  createdAt: Date;
  updatedAt: Date;
}

export interface FallbackDocument {
  id: string;
  userId: string;
  fileName: string;
  fileUrl: string;
  fileType: string;
  parsedText?: string | null;
  status: string;
  fileSize?: number | null;
  createdAt: Date;
}

export interface FallbackChunk {
  id: string;
  documentId: string;
  userId: string;
  content: string;
  subjectTag?: string | null;
  moduleIndex?: number | null;
  embedding?: number[] | null;
  createdAt: Date;
}

export interface FallbackCourse {
  id: string;
  userId: string;
  code: string;
  name: string;
  credits: number;
  color: string;
  createdAt: Date;
}

export interface FallbackScheduleBlock {
  id: string;
  userId: string;
  courseId?: string | null;
  title: string;
  startTime: Date;
  endTime: Date;
  isAutoGenerated: boolean;
  isRecurring: boolean;
  recurrenceRule?: string | null;
}

export interface FallbackTask {
  id: string;
  userId: string;
  courseId?: string | null;
  title: string;
  description?: string | null;
  dueDate?: Date | null;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: 'TODO' | 'IN_PROGRESS' | 'COMPLETED' | 'CUT';
  isCut: boolean;
  createdAt: Date;
}

export interface FallbackQuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
  explanation: string;
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  topic: string;
}

export interface FallbackQuiz {
  id: string;
  userId: string;
  courseId?: string | null;
  title: string;
  subjectTag: string;
  questions: FallbackQuizQuestion[];
  createdAt: Date;
}

export interface FallbackQuizAttempt {
  id: string;
  userId: string;
  quizId: string;
  score: number;
  total: number;
  accuracy: number;
  details: {
    questionId: string;
    selectedAnswer: number;
    isCorrect: boolean;
    explanation: string;
  }[];
  tutorFeedback?: string;
  createdAt: Date;
}

class InMemStore {
  users: Map<string, FallbackUser> = new Map();
  documents: Map<string, FallbackDocument> = new Map();
  chunks: Map<string, FallbackChunk> = new Map();
  courses: Map<string, FallbackCourse> = new Map();
  schedules: Map<string, FallbackScheduleBlock> = new Map();
  tasks: Map<string, FallbackTask> = new Map();
  quizzes: Map<string, FallbackQuiz> = new Map();
  quizAttempts: Map<string, FallbackQuizAttempt> = new Map();
  isPostgresReady: boolean = false;

  async checkDatabaseHealth(): Promise<boolean> {
    try {
      await prisma.$queryRaw`SELECT 1`;
      this.isPostgresReady = true;
      console.log('✅ Connected to PostgreSQL database with Prisma.');
      return true;
    } catch (err: any) {
      this.isPostgresReady = false;
      console.warn('ℹ️ PostgreSQL database connection not detected. Using high-performance in-memory persistence fallback for development.');
      return false;
    }
  }
}

export const memStore = new InMemStore();
