import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import { autoScheduleService } from '../services/autoScheduleService';
import { prisma, memStore, FallbackScheduleBlock, FallbackTask } from '../config/prisma';

const createEventSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  courseId: z.string().optional(),
  startTime: z.string(),
  endTime: z.string(),
  isRecurring: z.boolean().optional().default(false),
  recurrenceRule: z.string().optional(),
});

const uploadTimetableSchema = z.object({
  timetableText: z.string().min(5, 'Timetable content is required'),
});

const createTaskSchema = z.object({
  title: z.string().min(1, 'Task title is required'),
  description: z.string().optional(),
  courseId: z.string().optional(),
  dueDate: z.string().optional(),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']).default('MEDIUM'),
});

const updateTaskSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  status: z.enum(['TODO', 'IN_PROGRESS', 'COMPLETED', 'CUT']).optional(),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']).optional(),
  isCut: z.boolean().optional(),
});

export class PlannerController {
  /**
   * Get all schedule events (Class timetable + Auto-scheduled focus slots)
   */
  async getEvents(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;

      if (memStore.isPostgresReady) {
        const events = await prisma.scheduleBlock.findMany({
          where: { userId },
          include: { course: true },
          orderBy: { startTime: 'asc' },
        });
        res.status(200).json({ success: true, events });
      } else {
        const events = Array.from(memStore.schedules.values())
          .filter((e) => e.userId === userId)
          .sort((a, b) => new Date(a.startTime).getTime() - new Date(b.startTime).getTime())
          .map((e) => {
            const course = e.courseId ? memStore.courses.get(e.courseId) : null;
            return {
              ...e,
              course,
            };
          });
        res.status(200).json({ success: true, events });
      }
    } catch (error) {
      next(error);
    }
  }

  /**
   * Create custom calendar event
   */
  async createEvent(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const data = createEventSchema.parse(req.body);

      const blockId = `event_${Date.now()}_${Math.random().toString(36).substr(2, 7)}`;
      const startTime = new Date(data.startTime);
      const endTime = new Date(data.endTime);

      if (memStore.isPostgresReady) {
        const event = await prisma.scheduleBlock.create({
          data: {
            id: blockId,
            userId,
            title: data.title,
            courseId: data.courseId || null,
            startTime,
            endTime,
            isRecurring: data.isRecurring,
            recurrenceRule: data.recurrenceRule || null,
            isAutoGenerated: false,
          },
        });
        res.status(201).json({ success: true, event });
      } else {
        const event: FallbackScheduleBlock = {
          id: blockId,
          userId,
          title: data.title,
          courseId: data.courseId || null,
          startTime,
          endTime,
          isRecurring: data.isRecurring,
          recurrenceRule: data.recurrenceRule || null,
          isAutoGenerated: false,
        };
        memStore.schedules.set(blockId, event);
        res.status(201).json({ success: true, event });
      }
    } catch (error) {
      next(error);
    }
  }

  /**
   * Delete calendar event
   */
  async deleteEvent(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const id = req.params.id as string;

      if (memStore.isPostgresReady) {
        await prisma.scheduleBlock.deleteMany({
          where: { id, userId },
        });
      } else {
        memStore.schedules.delete(id);
      }

      res.status(200).json({ success: true, message: 'Schedule event removed' });
    } catch (error) {
      next(error);
    }
  }

  /**
   * Ingest and Parse Class Timetable
   */
  async uploadTimetable(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const { timetableText } = uploadTimetableSchema.parse(req.body);

      const slots = autoScheduleService.parseTimetableText(timetableText);
      const insertedCount = await autoScheduleService.ingestTimetable(userId, slots);

      res.status(200).json({
        success: true,
        message: `Successfully ingested ${insertedCount} recurring timetable class blocks.`,
        slotsCount: slots.length,
      });
    } catch (error) {
      next(error);
    }
  }

  /**
   * Trigger Conflict-Free Auto-Scheduling Algorithm
   */
  async autoSchedule(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const allocatedBlocks = await autoScheduleService.generateAutoSchedule(userId);

      res.status(200).json({
        success: true,
        message: `Allocated ${allocatedBlocks.length} conflict-free focused study blocks around your classes.`,
        allocatedCount: allocatedBlocks.length,
        blocks: allocatedBlocks,
      });
    } catch (error) {
      next(error);
    }
  }

  /**
   * Get Tasks with filtering
   */
  async getTasks(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const statusFilter = req.query.status as string | undefined;

      if (memStore.isPostgresReady) {
        const tasks = await prisma.task.findMany({
          where: {
            userId,
            ...(statusFilter ? { status: statusFilter as any } : {}),
          },
          include: { course: true },
          orderBy: { createdAt: 'desc' },
        });
        res.status(200).json({ success: true, tasks });
      } else {
        let tasks = Array.from(memStore.tasks.values()).filter((t) => t.userId === userId);
        if (statusFilter) {
          tasks = tasks.filter((t) => t.status === statusFilter);
        }
        res.status(200).json({ success: true, tasks });
      }
    } catch (error) {
      next(error);
    }
  }

  /**
   * Create Academic Task
   */
  async createTask(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const data = createTaskSchema.parse(req.body);

      const taskId = `task_${Date.now()}_${Math.random().toString(36).substr(2, 7)}`;
      const dueDate = data.dueDate ? new Date(data.dueDate) : null;

      if (memStore.isPostgresReady) {
        const task = await prisma.task.create({
          data: {
            id: taskId,
            userId,
            title: data.title,
            description: data.description || null,
            courseId: data.courseId || null,
            dueDate,
            priority: data.priority,
            status: 'TODO',
            isCut: false,
          },
        });
        res.status(201).json({ success: true, task });
      } else {
        const task: FallbackTask = {
          id: taskId,
          userId,
          title: data.title,
          description: data.description || null,
          courseId: data.courseId || null,
          dueDate,
          priority: data.priority,
          status: 'TODO',
          isCut: false,
          createdAt: new Date(),
        };
        memStore.tasks.set(taskId, task);
        res.status(201).json({ success: true, task });
      }
    } catch (error) {
      next(error);
    }
  }

  /**
   * Update Task Status or Priority
   */
  async updateTask(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const id = req.params.id as string;
      const data = updateTaskSchema.parse(req.body);

      if (memStore.isPostgresReady) {
        const updated = await prisma.task.update({
          where: { id },
          data: {
            ...(data.title ? { title: data.title } : {}),
            ...(data.description ? { description: data.description } : {}),
            ...(data.status ? { status: data.status as any } : {}),
            ...(data.priority ? { priority: data.priority as any } : {}),
            ...(data.isCut !== undefined ? { isCut: data.isCut } : {}),
          },
        });
        res.status(200).json({ success: true, task: updated });
      } else {
        const task = memStore.tasks.get(id);
        if (!task || task.userId !== userId) {
          res.status(404).json({ success: false, error: 'Task not found' });
          return;
        }
        if (data.title) task.title = data.title;
        if (data.description !== undefined) task.description = data.description;
        if (data.status) task.status = data.status;
        if (data.priority) task.priority = data.priority;
        if (data.isCut !== undefined) task.isCut = data.isCut;

        memStore.tasks.set(id, task);
        res.status(200).json({ success: true, task });
      }
    } catch (error) {
      next(error);
    }
  }

  /**
   * Delete Task
   */
  async deleteTask(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const id = req.params.id as string;

      if (memStore.isPostgresReady) {
        await prisma.task.deleteMany({ where: { id, userId } });
      } else {
        memStore.tasks.delete(id);
      }

      res.status(200).json({ success: true, message: 'Task deleted successfully' });
    } catch (error) {
      next(error);
    }
  }

  /**
   * Run Academic Cut-List Triage Engine
   */
  async runCutListTriage(req: Request, res: Response, next: NextFunction): Promise<void> {
    try {
      const userId = req.user!.id;
      const isExamWindowNear = req.body.isExamWindowNear !== false;

      const result = await autoScheduleService.runCutListTriage(userId, isExamWindowNear);

      res.status(200).json({
        success: true,
        message: `Academic Triage Complete: Retained ${result.retainedCount} core degree tasks, triaged ${result.cutCount} non-essential tasks into cut-list.`,
        result,
      });
    } catch (error) {
      next(error);
    }
  }
}

export const plannerController = new PlannerController();
