import { prisma, memStore, FallbackScheduleBlock } from '../config/prisma';

export class CalendarExportService {
  /**
   * Format a date into iCalendar UTC timestamp: YYYYMMDDTHHMMSSZ
   */
  private formatICalDate(date: Date): string {
    const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);
    return (
      date.getUTCFullYear().toString() +
      pad(date.getUTCMonth() + 1) +
      pad(date.getUTCDate()) +
      'T' +
      pad(date.getUTCHours()) +
      pad(date.getUTCMinutes()) +
      pad(date.getUTCSeconds()) +
      'Z'
    );
  }

  /**
   * Generate RFC 5545 iCalendar string for user's schedule blocks
   */
  async generateICalFeed(userId: string): Promise<string> {
    let events: {
      id: string;
      title: string;
      startTime: Date;
      endTime: Date;
      isRecurring: boolean;
      recurrenceRule?: string | null;
      isAutoGenerated: boolean;
    }[] = [];

    if (memStore.isPostgresReady) {
      const dbEvents = await prisma.scheduleBlock.findMany({
        where: { userId },
      });
      events = dbEvents.map((e) => ({
        id: e.id,
        title: e.title,
        startTime: new Date(e.startTime),
        endTime: new Date(e.endTime),
        isRecurring: e.isRecurring,
        recurrenceRule: e.recurrenceRule,
        isAutoGenerated: e.isAutoGenerated,
      }));
    } else {
      events = Array.from(memStore.schedules.values())
        .filter((e) => e.userId === userId)
        .map((e) => ({
          id: e.id,
          title: e.title,
          startTime: new Date(e.startTime),
          endTime: new Date(e.endTime),
          isRecurring: e.isRecurring,
          recurrenceRule: e.recurrenceRule,
          isAutoGenerated: e.isAutoGenerated,
        }));
    }

    const now = new Date();
    const dtStamp = this.formatICalDate(now);

    let icsLines: string[] = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//ALTER Academic Operations & Planner//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:ALTER Academic Schedule',
      'X-WR-TIMEZONE:UTC',
    ];

    for (const evt of events) {
      const dtStart = this.formatICalDate(evt.startTime);
      const dtEnd = this.formatICalDate(evt.endTime);
      const description = evt.isAutoGenerated
        ? 'AI-Scheduled Focus Study Session generated by ALTER Academic Orchestrator'
        : 'Curriculum Lecture Timetable Block';

      icsLines.push('BEGIN:VEVENT');
      icsLines.push(`UID:${evt.id}@alter.quantum.edu`);
      icsLines.push(`DTSTAMP:${dtStamp}`);
      icsLines.push(`DTSTART:${dtStart}`);
      icsLines.push(`DTEND:${dtEnd}`);
      icsLines.push(`SUMMARY:${evt.title.replace(/[,;]/g, ' ')}`);
      icsLines.push(`DESCRIPTION:${description}`);
      icsLines.push('STATUS:CONFIRMED');

      if (evt.isRecurring && evt.recurrenceRule) {
        icsLines.push(`RRULE:${evt.recurrenceRule}`);
      }

      icsLines.push('END:VEVENT');
    }

    icsLines.push('END:VCALENDAR');
    return icsLines.join('\r\n');
  }
}

export const calendarExportService = new CalendarExportService();
