import { create } from 'zustand';
import api from '../lib/api';

export interface ScheduleEvent {
  id: string;
  courseId?: string | null;
  title: string;
  startTime: string;
  endTime: string;
  isAutoGenerated: boolean;
  isRecurring: boolean;
  recurrenceRule?: string | null;
  course?: {
    code: string;
    name: string;
    color: string;
    credits: number;
  } | null;
}

export interface TaskItem {
  id: string;
  courseId?: string | null;
  title: string;
  description?: string | null;
  dueDate?: string | null;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: 'TODO' | 'IN_PROGRESS' | 'COMPLETED' | 'CUT';
  isCut: boolean;
  course?: {
    code: string;
    name: string;
    color: string;
  } | null;
}

interface PlannerState {
  events: ScheduleEvent[];
  tasks: TaskItem[];
  isLoading: boolean;
  isScheduling: boolean;
  statusMessage: string | null;

  fetchEvents: () => Promise<void>;
  fetchTasks: () => Promise<void>;
  createTask: (data: {
    title: string;
    description?: string;
    courseId?: string;
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
    dueDate?: string;
  }) => Promise<boolean>;
  updateTaskStatus: (id: string, status: 'TODO' | 'IN_PROGRESS' | 'COMPLETED' | 'CUT', isCut?: boolean) => Promise<boolean>;
  deleteTask: (id: string) => Promise<boolean>;
  runAutoSchedule: () => Promise<number>;
  uploadTimetable: (text: string) => Promise<boolean>;
  runCutListTriage: (isExamWindowNear?: boolean) => Promise<any>;
}

const INITIAL_DEMO_EVENTS: ScheduleEvent[] = [
  {
    id: 'evt_1',
    title: 'CS402: Raft Consensus & Leader Election',
    startTime: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 3.5 * 3600 * 1000).toISOString(),
    isAutoGenerated: false,
    isRecurring: true,
    recurrenceRule: 'FREQ=WEEKLY;BYDAY=MO,WE,FR',
    course: { code: 'CS402', name: 'Distributed Systems', color: '#06B6D4', credits: 4 },
  },
  {
    id: 'evt_2',
    title: 'ROB701: Sensor Fusion & SLAM Lab',
    startTime: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 7 * 3600 * 1000).toISOString(),
    isAutoGenerated: false,
    isRecurring: true,
    recurrenceRule: 'FREQ=WEEKLY;BYDAY=TU,TH',
    course: { code: 'ROB701', name: 'Swarm Robotics', color: '#8B5CF6', credits: 4 },
  },
  {
    id: 'evt_3',
    title: '⚡ AI Focus Block: Raft Log Compaction Implementation',
    startTime: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    endTime: new Date(Date.now() + 10 * 3600 * 1000).toISOString(),
    isAutoGenerated: true,
    isRecurring: false,
    course: { code: 'CS402', name: 'Distributed Systems', color: '#10B981', credits: 4 },
  },
];

const INITIAL_DEMO_TASKS: TaskItem[] = [
  {
    id: 'task_1',
    title: 'Implement Raft Log Compaction & Heartbeat Invariants',
    description: 'Core degree capstone assignment covering linearizable reads and cluster membership changes.',
    priority: 'CRITICAL',
    status: 'TODO',
    isCut: false,
    course: { code: 'CS402', name: 'Distributed Systems', color: '#06B6D4' },
  },
  {
    id: 'task_2',
    title: 'Extended Kalman Filter (EKF) Covariance Tuning',
    description: 'Tune covariance Q and R matrices for noisy IMU / lidar state estimation.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    isCut: false,
    course: { code: 'ROB701', name: 'Swarm Robotics', color: '#8B5CF6' },
  },
  {
    id: 'task_3',
    title: 'Format Reference Appendix in LaTeX for Optional Colloquium',
    description: 'Non-graded elective reading list formatting.',
    priority: 'LOW',
    status: 'CUT',
    isCut: true,
    course: { code: 'ELEC101', name: 'Academic Writing', color: '#64748B' },
  },
];

export const usePlannerStore = create<PlannerState>((set, get) => ({
  events: INITIAL_DEMO_EVENTS,
  tasks: INITIAL_DEMO_TASKS,
  isLoading: false,
  isScheduling: false,
  statusMessage: null,

  fetchEvents: async () => {
    try {
      const res = await api.get('/planner/events');
      if (res.data.success && res.data.events.length > 0) {
        set({ events: res.data.events });
      } else {
        set({ events: INITIAL_DEMO_EVENTS });
      }
    } catch (err) {
      console.warn('Using demo planner events fallback');
      set({ events: INITIAL_DEMO_EVENTS });
    }
  },

  fetchTasks: async () => {
    try {
      const res = await api.get('/tasks');
      if (res.data.success && res.data.tasks.length > 0) {
        set({ tasks: res.data.tasks });
      } else {
        set({ tasks: INITIAL_DEMO_TASKS });
      }
    } catch (err) {
      console.warn('Using demo tasks fallback');
      set({ tasks: INITIAL_DEMO_TASKS });
    }
  },

  createTask: async (payload) => {
    try {
      const res = await api.post('/tasks', payload);
      if (res.data.success) {
        await get().fetchTasks();
        return true;
      }
      return false;
    } catch (err) {
      console.error('Failed to create task:', err);
      return false;
    }
  },

  updateTaskStatus: async (id, status, isCut) => {
    try {
      const res = await api.patch(`/tasks/${id}`, {
        status,
        ...(isCut !== undefined ? { isCut } : {}),
      });
      if (res.data.success) {
        set((state) => ({
          tasks: state.tasks.map((t) => (t.id === id ? { ...t, status, isCut: isCut ?? t.isCut } : t)),
        }));
        return true;
      }
      return false;
    } catch (err) {
      console.error('Failed to update task:', err);
      return false;
    }
  },

  deleteTask: async (id) => {
    try {
      const res = await api.delete(`/tasks/${id}`);
      if (res.data.success) {
        set((state) => ({
          tasks: state.tasks.filter((t) => t.id !== id),
        }));
        return true;
      }
      return false;
    } catch (err) {
      console.error('Failed to delete task:', err);
      return false;
    }
  },

  runAutoSchedule: async () => {
    set({ isScheduling: true, statusMessage: 'Calculating optimal conflict-free study blocks...' });
    try {
      const res = await api.post('/planner/auto-schedule');
      if (res.data.success) {
        await get().fetchEvents();
        set({
          isScheduling: false,
          statusMessage: `Allocated ${res.data.allocatedCount} focused study blocks!`,
        });
        setTimeout(() => set({ statusMessage: null }), 4000);
        return res.data.allocatedCount;
      }
      set({ isScheduling: false, statusMessage: null });
      return 0;
    } catch (err) {
      console.error('Auto-schedule failed:', err);
      set({ isScheduling: false, statusMessage: 'Auto-scheduling failed' });
      return 0;
    }
  },

  uploadTimetable: async (timetableText) => {
    set({ isLoading: true });
    try {
      const res = await api.post('/planner/timetable-upload', { timetableText });
      if (res.data.success) {
        await get().fetchEvents();
        set({ isLoading: false, statusMessage: res.data.message });
        setTimeout(() => set({ statusMessage: null }), 4000);
        return true;
      }
      set({ isLoading: false });
      return false;
    } catch (err) {
      console.error('Timetable upload failed:', err);
      set({ isLoading: false });
      return false;
    }
  },

  runCutListTriage: async (isExamWindowNear = true) => {
    set({ isLoading: true });
    try {
      const res = await api.patch('/tasks/cut-list', { isExamWindowNear });
      if (res.data.success) {
        await get().fetchTasks();
        set({
          isLoading: false,
          statusMessage: `Triage complete: Cut ${res.data.result.cutCount} non-essential tasks`,
        });
        setTimeout(() => set({ statusMessage: null }), 4000);
        return res.data.result;
      }
      set({ isLoading: false });
      return null;
    } catch (err) {
      console.error('Cut-list triage failed:', err);
      set({ isLoading: false });
      return null;
    }
  },
}));
